### ISSUE TITLE
Problems 

### ISSUE THREAD

**Issue by calebsexy** [SilverGoLt/h-vshop#1]
First Problem
![image](https://user-images.githubusercontent.com/92877164/182323477-e166c6b1-d303-438e-a819-621531276e33.png)

 Second Problem (when i press E on the point)
![image](https://user-images.githubusercontent.com/92877164/182323573-2a2ae9f4-c2a0-465e-bc5a-a7b7c9a238b5.png)

**Comment by SilverGoLt** [comment]
Hi @qmitroxdev,
Seems like you might be running quite a old version of es_extended that's why it's not being able to get ESX functions.
You can resolve this by upadting your es_extended :)

**Comment by frazz1234** [comment]
All good for me ! :)

**Comment by frazz1234** [comment]
There is a way you could add a test drive ? And the possibility to change the view whit the arrow? Thks

**Comment by SilverGoLt** [comment]
He's probably using an old es_extended version that doesn't support the @es_extended/imports.lua.

Regarding the test drive, I'm currently not working on this resource. It's just released for free for the community if someone wants to contribute towards it I'm happy to accept commits :)

**Comment by frazz1234** [comment]
Hoo :( im very bad whit html so I can't modify it... there is a way you can take sometime for add this thing ? It will be just ... amazing
