### ISSUE TITLE
es_extended Error (client side/client log)  (On es_extended 1.8.5)

### ISSUE THREAD

**Issue by LimnedMoon** [SilverGoLt/h-vshop#4]
Got this by open/ close the UI 

SCRIPT ERROR: es_extended/lua/scheduler.lua:479: attempt to concatenate a nil value (local 'err')

Using the latest esx release 1.8.5 from github/mycroft

Best Regards

**Comment by SilverGoLt** [comment]
Hi @Marc85BPG,
Thank you for logging this issue on GitHub, would you be able to provide a full screenshot of the error? Since this line doesn't really help me to identify which part of the H-VShop code is causing the issue.

Kind Regards
Haroki

**Comment by LimnedMoon** [comment]
Yes of course Bro.
![Screenshot_1](https://user-images.githubusercontent.com/17122774/193166520-f03b0d1c-84e0-4677-adea-6c49fbb98907.jpg)

A few more Background infos about using test-enviroment.
- ESX 1.8.5 (latest official release)
- oxmysql
- ox-lib
- ox-inventory
- ox-fuel

If you need more infos, tell me if i have your permit to DM you on discord. 
Best Regards

**Comment by SilverGoLt** [comment]
Couldn't replicate issue.
